version: '3.9'
services:
  dbs-api:
    container_name: api
    image: slotix/dbs-api
    entrypoint:
      - ./dbs-api
      - --nats=nats:4222
    ports:
      - 8020:8020
    depends_on:
      - nats

  dbs-source-reader:
    container_name: source-reader
    image: slotix/dbs-source-reader
    entrypoint:
      - ./dbs-source-reader
      - --nats=nats:4222
    ports:
      - 8021:8021
    depends_on:
      - nats

  dbs-target-writer:
    container_name: target-writer
    image: slotix/dbs-target-writer
    entrypoint:
      - ./dbs-target-writer
      - --nats=nats:4222
    ports:
      - 8022:8022
    depends_on:
      - nats

#  dbs-target-writer2:
#    container_name: target-writer2
#    image: slotix/dbs-target-writer
#    entrypoint:
#      - ./dbs-target-writer
#      - --nats=nats:4222
#    ports:
#      - 8023:8023
#    depends_on:
#      - nats
#
#  dbs-target-writer3:
#    container_name: target-writer3
#    image: slotix/dbs-target-writer
#    entrypoint:
#      - ./dbs-target-writer
#      - --nats=nats:4222
#    ports:
#      - 8024:8024
#    depends_on:
#      - nats

  nats:
    container_name: nats
    image: nats
    entrypoint: /nats-server
    command: "--jetstream -m 8222 --store_dir /data/nats-server"
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - ./_storage/nats:/data/nats-server/jetstream

  prometheus:
    image: slotix/dbs-prometheus:latest
    container_name: prom
    user: root
    ports:
      - 9090:9090
    # command:
    #   - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      # - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./_storage/prometheus:/prometheus

  
  postgres:
    container_name: postgres
    image: slotix/dbs-postgres:15-alpine
    # build: ./config/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres
    ports:
      - '5432:5432'


  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #      - 8080:8080
  #
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    #restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@dbconvert.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    # volumes: 
      # !!!! sudo chown -R 5050:5050 <host_directory>
      # !!!! sudo chown 5050:5050 client.key client.crt ca.crt
      # - ./_storage/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    network_mode: host
