version: '3.9'
services:
  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-c /etc/nats/nats.conf --server_name n1m1 --js --cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 --routes=nats://nats:6222"
    volumes:
      - ./config/:/etc/nats
  nats-1:
    image: nats
    container_name: nats1
    command: "-c /etc/nats/nats.conf --server_name n1m2 --js  --cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://nats:6222"
    depends_on: [ "nats" ]
    volumes:
      - ./config/:/etc/nats
  nats-2:
    image: nats
    container_name: nats2
    command: "-c /etc/nats/nats.conf --server_name n1m3 --js  --cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://nats:6222"
    depends_on: [ "nats" ]
    volumes:
      - ./config/:/etc/nats
