global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "rules.yml"

scrape_configs:
  # Scrape the Source Reader every second.
  - job_name: 'source'
    scrape_interval: 1s
    static_configs:
    - targets: ['dbs-source-reader:8021']

  # Scrape the Target Writers every second.
  - job_name: 'target'
    scrape_interval: 1s
    static_configs:
    - targets: ['dbs-target-writer:8022', 'dbs-target-writer2:8023', 'dbs-target-writer3:8024']
