services:
  dbs-api:
    container_name: api
    image: slotix/dbs-api
    entrypoint:
      - ./dbs-api
      - --nats=nats:4222
    ports:
      - 8020:8020
    depends_on:
      - nats
    volumes:
      - ./mysql2pg.json:/mysql2pg.json:ro

  dbs-source-reader:
    container_name: source-reader
    image: slotix/dbs-source-reader
    entrypoint:
      - ./dbs-source-reader
      - --nats=nats:4222
    ports:
      - 8021:8021
    depends_on:
      - dbs-api

  dbs-target-writer:
    container_name: target-writer
    image: slotix/dbs-target-writer
    entrypoint:
      - ./dbs-target-writer
      - --host=dbs-target-writer:8022  
      - --nats=nats:4222
      - --prometheus=http://prometheus:9090
    ports:
      - 8022:8022
    depends_on:
      - dbs-api


  dbs-target-writer2:
    container_name: target-writer2
    image: slotix/dbs-target-writer
    entrypoint:
      - ./dbs-target-writer
      - --host=dbs-target-writer2:8023  
      - --nats=nats:4222
      - --prometheus=http://prometheus:9090
    ports:
      - 8023:8023
    depends_on:
      - dbs-api


  dbs-target-writer3:
    container_name: target-writer3
    image: slotix/dbs-target-writer
    entrypoint:
      - ./dbs-target-writer
      - --host=dbs-target-writer3:8024  
      - --nats=nats:4222
      - --prometheus=http://prometheus:9090
    ports:
      - 8024:8024
    depends_on:
      - dbs-api

  nats:
    container_name: nats
    image: nats
    entrypoint: /nats-server
    command: "--jetstream -m 8222 --store_dir /data/nats-server"
    ports:
      - 4222:4222
      - 8222:8222
      - 8081:8081
    # volumes:
      # - ../_storage/nats:/data/nats-server/jetstream

  prometheus:
    image: slotix/dbs-prometheus:latest
    container_name: prom
    user: root
    ports:
      - 9090:9090
    # command:
      # - --config.file=/etc/prometheus/prometheus.yml
    # volumes:
    #   - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    #   - ../_storage/prometheus:/prometheus


  mysql-source:
    container_name: mysql-source
    build: ./source 
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'


  postgres-target:
    container_name: postgres-target
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres
    # volumes:
      # - ./_storage/postgres-data:/var/lib/postgresql/data
      # - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: adminer
    # restart: always
    ports:
       - 8080:8080

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    #restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@dbconvert.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres-target
    # volumes: 
      # !!!! sudo chown -R 5050:5050 <host_directory>
      # !!!! sudo chown 5050:5050 client.key client.crt ca.crt
      # - ./_storage/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    network_mode: host
