version: '3.9'
services:
  dbs-api:
    container_name: api
    image: slotix/dbs-api
    entrypoint:
      - ./dbs-api
      - --nats=nats:4222
    ports:
      - 8020:8020
    depends_on:
      - nats

  dbs-source-reader:
    container_name: source-reader
    image: slotix/dbs-source-reader
    entrypoint:
      - ./dbs-source-reader
      - --nats=nats:4222
    ports:
      - 8021:8021
    depends_on:
      - nats

  dbs-target-writer:
    container_name: target-writer
    image: slotix/dbs-target-writer
    entrypoint:
      - ./dbs-target-writer
      - --nats=nats:4222
    ports:
      - 8022:8022
    depends_on:
      - nats

#  dbs-target-writer2:
#    container_name: target-writer2
#    image: slotix/dbs-target-writer
#    entrypoint:
#      - ./dbs-target-writer
#      - --nats=nats:4222
#    ports:
#      - 8023:8023
#    depends_on:
#      - nats
#
#  dbs-target-writer3:
#    container_name: target-writer3
#    image: slotix/dbs-target-writer
#    entrypoint:
#      - ./dbs-target-writer
#      - --nats=nats:4222
#    ports:
#      - 8024:8024
#    depends_on:
#      - nats

  nats:
    container_name: nats
    image: nats
    entrypoint: /nats-server
    command: "--jetstream -m 8222 --store_dir /data/nats-server"
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - ./_storage/nats:/data/nats-server/jetstream

  prometheus:
    image: slotix/dbs-prometheus:latest
    container_name: prom
    user: root
    ports:
      - 9090:9090
    # command:
    #   - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      # - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus
