version: '3.9'
services:
  dbs-api:
    container_name: api
    image: slotix/dbs-api
    entrypoint:
      - ./dbs-api
      - --nats=nats:4222
    ports:
      - 8020:8020
    depends_on:
      - nats
    volumes:
      - ./mysql2pg.json:/mysql2pg.json:ro

  dbs-source-reader:
    container_name: source-reader
    image: slotix/dbs-source-reader
    entrypoint:
      - ./dbs-source-reader
      - --nats=nats:4222
    ports:
      - 8021:8021
    depends_on:
      - dbs-api

  dbs-target-writer:
    container_name: target-writer
    image: slotix/dbs-target-writer
    entrypoint:
      - ./dbs-target-writer
      - --host=dbs-target-writer:8022  
      - --nats=nats:4222
      - --prometheus=http://prometheus:9090
    ports:
      - 8022:8022
    depends_on:
      - dbs-api


  dbs-target-writer2:
    container_name: target-writer2
    image: slotix/dbs-target-writer
    entrypoint:
      - ./dbs-target-writer
      - --host=dbs-target-writer2:8023  
      - --nats=nats:4222
      - --prometheus=http://prometheus:9090
    ports:
      - 8023:8023
    depends_on:
      - dbs-api


  dbs-target-writer3:
    container_name: target-writer3
    image: slotix/dbs-target-writer
    entrypoint:
      - ./dbs-target-writer
      - --host=dbs-target-writer3:8024  
      - --nats=nats:4222
      - --prometheus=http://prometheus:9090
    ports:
      - 8024:8024
    depends_on:
      - dbs-api

  nats:
    container_name: nats
    image: nats
    entrypoint: /nats-server
    command: "--jetstream -m 8222 --store_dir /data/nats-server"
    ports:
      - 4222:4222
      - 8222:8222
      - 8081:8081
    # volumes:
      # - ../_storage/nats:/data/nats-server/jetstream

  prometheus:
    image: slotix/dbs-prometheus:latest
    container_name: prom
    user: root
    ports:
      - 9090:9090
    # command:
      # - --config.file=/etc/prometheus/prometheus.yml
    # volumes:
    #   - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    #   - ../_storage/prometheus:/prometheus
